---
- name: Install RPM packages
  dnf:
    name:
      - git
      - vim
      - libpq-devel
      - sqlite3
      - poetry
    state: present

- name: configure fedora-messaging to point at tinystage rabbitmq
  lineinfile:
    path: /etc/fedora-messaging/config.toml
    regexp: 'amqp_url = "amqp://"'
    line: 'amqp_url = "amqp://fedoramessages:fedoramessages@tinystage.tinystage.test"' # gitleaks:allow

- name: Setup development instance of tahrir
  command: poetry install
  become: yes
  become_user: vagrant
  args:
    chdir: /home/vagrant/tahrir

- name: copy the config files
  copy:
    src: "{{ item }}"
    dest: /home/vagrant/{{ item }}
    mode: 0644
    owner: vagrant
    group: vagrant
  loop:
    - tahrir.cfg
    - alembic.ini

- name: get the fedora badges
  git:
    repo: https://pagure.io/fedora-badges.git
    dest: /home/vagrant/fedora-badges

- name: Create or update the database
  command: poetry run flask tahrir sync-db
  environment:
    FLASK_CONFIG: /home/vagrant/tahrir.cfg
    FLASK_APP: /home/vagrant/tahrir/tahrir/app.py
    FLASK_DEBUG: 1
  become: yes
  become_user: vagrant
  args:
    chdir: /home/vagrant/tahrir

- name: load the fedora badges in the DB
  command: poetry run flask tahrir load-badges
  environment:
    FLASK_CONFIG: /home/vagrant/tahrir.cfg
    FLASK_APP: /home/vagrant/tahrir/tahrir/app.py
    FLASK_DEBUG: 1
  become: yes
  become_user: vagrant
  args:
    chdir: /home/vagrant/tahrir

- name: Install the systemd unit files
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    mode: 0644
  loop:
    - synced-folder@.service
    - tahrir.service

- name: Enable and start services using systemd
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: started
  loop:
    - synced-folder@tahrir.service
    - tahrir.service
