---
- name: Setup development instance of tahrir
  command: poetry install
  become: yes
  become_user: vagrant
  args:
      chdir: /home/vagrant/tahrir

- name: copy the developemnt.ini file
  copy:
    src: development.ini
    dest: /home/vagrant/development.ini
    mode: 0644
    owner: vagrant
    group: vagrant


- name: copy the secret.ini file
  copy:
    src: secret.ini
    dest: /home/vagrant/secret.ini
    mode: 0644
    owner: vagrant
    group: vagrant


- command: poetry run initialize_tahrir_db /home/vagrant/development.ini
  become: yes
  become_user: vagrant
  args:
      chdir: /home/vagrant/tahrir

- name: Install the systemd unit files for tahrir service
  copy:
    src: tahrir.service
    dest: /etc/systemd/system/tahrir.service
    mode: 0644

- name: Start tahrir service using systemd
  systemd:
    state: started
    name: tahrir
    daemon_reload: yes
    enabled: yes
