name: Tests
on: [push,pull_request]
jobs:
  check-with-tox:
    name: Check with tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fedora-python/tox-github-action@main
        with:
          # The tox environment to run
          # Default: py38 (subject to change as new Python releases come out)
          tox_env: py38
